### ISSUE TITLE
double segfault 

### ISSUE THREAD

**Issue by ghost** [phire/doom3.gpl#9]
I get a double segfault when building against the current commits for this repo.

**Comment by phire** [comment]
For my notes so I don't forget: 

windowshasyou has a custom linux distro build directly from upstream sources. This is probably whats causing the issue.

btw, have you manged to get gdb running so that we can get a backtrace windowshasyou?

**Comment by phire** [comment]
Apparently this was caused by some custom gcc/glibc hardening patches to do with randomizing memory allocation.
